name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run Pylint
        run: |
          echo "=== Pylint Code Quality Check ==="
          pylint --output-format=text $(find . -name "*.py" -not -path "./.venv/*" -not -path "./tests/*" -not -path "./data/*" -not -path "./output/*") || true
          
      - name: Generate Pylint report
        run: |
          pylint --output-format=json $(find . -name "*.py" -not -path "./.venv/*" -not -path "./tests/*" -not -path "./data/*" -not -path "./output/*") > pylint-results.json || true
          
      - name: Upload Pylint results
        uses: actions/upload-artifact@v4
        with:
          name: pylint-results
          path: pylint-results.json
